<style>
.msgbod{
	display: inline-block;
    position: relative;
    top: 0;
    bottom: 0;
    left: 20%;
    right: 20%;
    width: 750px;
    height: 120px;
    margin: auto;
}
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}
.page-title-wrapper
{
    text-align: center;
}

/*tr:nth-child(even) {
    background-color: #dddddd;
}*/
</style>
<h3 style="text-align: center;">We Have Received Your Payment Successfully !</h3>
<div class="actions-toolbar">
    <div class="primary">
        <a href="\"><button class="action primary continue">Continue Shopping</button></a>
    </div>
</div>