<?php if($block->getPaymentMethod() == $block->getConfigPaymentData()) {?>
<div class="rk button">
	
<?php
    echo "<br><h2 align='center'>Order successfully initiated. Please wait we are redirecting you to SSLCommerz...</h2><br>";
    
	# echo "<script>window.location.href = '". $sslcz['GatewayPageURL'] ."';</script>";
	echo "<meta http-equiv='refresh' content='0;url=".$block->getPostData()."'>";
	# header("Location: ". $sslcz['GatewayPageURL']);
?>

<?php } ?>